Feature/modifications for data team
Sysvale/cookiecutter-flask-minimal pull request #1
Opened 2020-06-18 18:53 UTC by genivalrm

2020-06-18 21:37 UTC, elaynelemos commented
Fora a parte de que tem 10 commits. Tá suave. rs

2020-06-18 21:42 UTC, elaynelemos commented on {{cookiecutter.package_name}}/docker-compose.yml
> +version: "3.7"
Ainda vai precisar ver que modificações precisam ser feitas no docker. Sugiro que seja um PR separado.

2020-06-18 21:45 UTC, elaynelemos requested changes
Docker em PR separado.

2020-06-23 15:39 UTC, denissonleal commented on cookiecutter.json
> +}
parece que aqui falta um linha. Configure teu editor pra nao ter esses problemas

2020-06-23 15:41 UTC, denissonleal approved these changes
Fora o tamanho do merge acho que ta ok. Tente fazer merges menores

2020-07-16 13:36 UTC, LEMSantos approved these changes

2020-07-16 13:41 UTC, merged